import type { GuideArticle } from "./types";

type GuideExtra = {
  start: string;
  goal: string;
  result: string;
  risk: string;
  mapMarkerId?: string;
  faqQuestion: string;
  faqAnswer: string;
};

export type GuideFaq = { question: string; answer: string };

export const CURRENT_VERIFICATION = "Retail build · checked through Balance Patch 1";

export const guideExtras: Record<string, GuideExtra> = {
  "shell-locations": { start: "Marrow Keep / Zhirelle", goal: "Unlock the eight permanent Shells", result: "Full playable roster", risk: "Balance Patch 1 changed map reveals from Glimpses to Gloom", faqQuestion: "Does Harros count as one of the eight permanent Shells?", faqAnswer: "No. Harros is playable during the prologue, while the permanent launch roster contains Tiel, Proxima, Eredrim, Gragu, Smert, Lazlo, Genessa, and Sariel." },
  tarstones: { start: "Field pickups and Tarforge", goal: "Build four compatible Tarstone categories", result: "Weapon and Sidearm modifiers", risk: "Beta lists contain outdated totals and locations", faqQuestion: "How many Tarstones are in the retail achievement route?", faqAnswer: "Current launch collectible reporting identifies 75 Tarstones for the Stoned achievement family. Older beta guides list much smaller totals and should not be used as a retail checklist." },
  "shell-tier-list": { start: "Eight permanent Shells", goal: "Choose a body for the current problem", result: "Role-based first-run ranking", risk: "Patch balance and execution can move tiers", faqQuestion: "Which Shell is safest for a blind first playthrough?", faqAnswer: "Eredrim is the safest durability pick, while Tiel offers the strongest early mobility when the player already trusts late-dodge timing." },
  "weapon-tier-list": { start: "Eight primary weapons", goal: "Match reach, speed, and Break to a Shell", result: "Balance Patch 1-aware upgrade choice", risk: "Patch buffs changed Great Martyr, tracking, and Sidearm value", faqQuestion: "Should every weapon be upgraded evenly?", faqAnswer: "No. Develop one reliable primary weapon first, then test alternatives at base level before committing rare smithing materials." },
  baghead: { start: "Desolate Peak / Outskirts of Nochte", goal: "Complete the empty-handed request", result: "Bag Holder scene and trophy", risk: "Carrying Special Moonshine gives the wrong response", faqQuestion: "Does the Baghead credits sequence end the real campaign?", faqAnswer: "No. It is a joke ending sequence, and normal progression can continue from the nearby Beacon afterward." },
  "duality-stone": { start: "Tarstone testing setup", goal: "Verify the reported double-strike interaction", result: "Conditional damage option", risk: "Exact behavior remains build-sensitive", faqQuestion: "Is every Duality Stone claim confirmed?", faqAnswer: "No. The page separates reproducible behavior from player reports and recommends testing against a repeatable enemy before investing." },
  "crypt-key": { start: "Illusionist's Cache / Desolate Peak", goal: "Open Hall of Echoes", result: "Optional dungeon access", risk: "Crypt, Chapel, Blackmarrow, and Blackwater are different keys", mapMarkerId: "crypt-key", faqQuestion: "Where is the Crypt Key used?", faqAnswer: "Use it on the locked Hall of Echoes entrance in northeastern Fainweald; it does not open the Shrine of Trials or Shell Shade chests." },
  axatana: { start: "City route in Mammon", goal: "Claim the transforming primary weapon", result: "Katana speed plus axe commitment", risk: "The pickup is not a Corrupted Gate reward", mapMarkerId: "weapon-axatana", faqQuestion: "Is Axatana one weapon or two?", faqAnswer: "It is one transforming primary weapon with fast katana and committed axe forms, so upgrades apply to the shared armament." },
  bosses: { start: "Six Corrupted Gates", goal: "Recover Ova and open Unfound Path", result: "Major campaign progression", risk: "Dungeon anchors are not outdoor arena coordinates", mapMarkerId: "gate-glutted-mire", faqQuestion: "Can the six Gate bosses be fought in any order?", faqAnswer: "Exploration is flexible within the regional structure, but routes and access requirements still make some fights more practical after nearby Beacons and upgrades are secured." },
  "final-boss": { start: "Hidden Nave / Unfound Path", goal: "Defeat Zmey the Unbidden", result: "Campaign completion and post-game access", risk: "Send Ova starts NG+ only when selected later", mapMarkerId: "boss-zmey", faqQuestion: "Does defeating Zmey automatically begin New Game Plus?", faqAnswer: "No. The current world remains available until Send Ova is selected at the Marrow Keep Gloom Siphon." },
  eredrim: { start: "Citadel of Penance", goal: "Defeat the Warden and claim the Shell", result: "Durability-focused permanent Shell", risk: "Health does not protect against red or persistent attacks", mapMarkerId: "shell-eredrim", faqQuestion: "Is Eredrim a good first main?", faqAnswer: "Yes for players who value survivability and learning time, especially once the route to Citadel of Penance is open." },
  beacons: { start: "Regional Beacon network", goal: "Cleanse and secure travel anchors", result: "Rest, progression, and fast-travel access", risk: "A visible structure may still require its interior objective", mapMarkerId: "marrow-keep", faqQuestion: "Does touching a Beacon always cleanse it?", faqAnswer: "No. Some Beacons require a short interior, enemy clear, or corruption objective before their full function becomes available." },
  "shell-points": { start: "Individual Shell progression", goal: "Strengthen a proven combat loop", result: "Shell-specific active and passive upgrades", risk: "Shell Points, Glimpses, and Gloom are different", faqQuestion: "Do Shell Points transfer between Shells?", faqAnswer: "Treat them as body-specific progression and verify the active Shell before spending; Glimpses separately gate Bond tiers and memories." },
  walkthrough: { start: "Prologue and Marrow Keep", goal: "Clear six Gates, Unfound Path, and Zmey", result: "Main campaign completion", risk: "Optional content can be postponed but Send Ova resets the world", mapMarkerId: "marrow-keep", faqQuestion: "Can cleanup continue after the final boss?", faqAnswer: "Yes. Defeating Zmey does not force NG+; remain in the current cycle until you deliberately select Send Ova." },
  genessa: { start: "Revenant Graves", goal: "Recover Sester's Censer and finish the memory", result: "Genessa, the Wayward", risk: "Zhirelle's reveal alone cannot complete this unlock", mapMarkerId: "shell-genessa", faqQuestion: "Does Genessa cost Glimpses to unlock?", faqAnswer: "No. Her route uses Sester's Censer, Sester Secundus, and a Marrow Keep hand-in rather than a Glimpse purchase." },
  glimpse: { start: "Beacons, fixed chests, and NPC rewards", goal: "Fund one main Shell's Bond and memories", result: "Balance Patch 1 preserves Glimpses by moving map reveals to Gloom", risk: "No verified infinite retail farm currently exists", mapMarkerId: "marrow-keep", faqQuestion: "Can ordinary enemies be farmed for infinite Glimpses?", faqAnswer: "No repeatable ordinary-enemy method is verified. Balance Patch 1 instead makes Shell map reveals cost Gloom and refunds previously spent reveal Glimpses." },
  "patch-notes": { start: "Official retail update posts", goal: "Separate live fixes from beta history", result: "Balance Patch 1 and current compatibility guidance", risk: "PC is live first; console rollout follows certification", faqQuestion: "What is the latest verified retail update?", faqAnswer: "Balance Patch 1 is the latest verified update. It changes the economy, enemies, bosses, weapons, Guard, Tarstones, crashes, and performance; PC launched first with consoles announced shortly after." },
  editions: { start: "Standard, Devout, and PS5 Revered", goal: "Choose by lasting contents", result: "Correct platform and package", risk: "Advanced access has ended and collector stock varies", faqQuestion: "Does Devout include extra gameplay?", faqAnswer: "Its lasting premium content is the eight Obsidian Shell skins; the advanced-access timing ended at worldwide launch." },
  gragu: { start: "One-Legged Wolf Tavern", goal: "Bring the Heart of Vatra", result: "Gragu, the Insatiable", risk: "Collect Berserker's Stone before leaving the temple", mapMarkerId: "shell-gragu", faqQuestion: "Can the Heart of Vatra be used on another character?", faqAnswer: "No verified alternate use exists. Hand it to Gragu to complete his request and unlock the Shell." },
  "blackmarrow-key": { start: "Night Mode and hidden routes", goal: "Open Marrow Keep Shell Shade chests", result: "Base-game cosmetic Shades", risk: "Do not confuse Blackmarrow with Blackwater, Crypt, or Chapel", mapMarkerId: "key-blackmarrow-marrow", faqQuestion: "Are Blackmarrow Shades part of Devout Edition?", faqAnswer: "No. Blackmarrow chests are base-game cosmetic progression; Devout's Obsidian Shell set is a separate edition benefit." },
  smert: { start: "Prophet's Rest", goal: "Activate three blood pools and win The Convert", result: "Smert plus My Brether", risk: "Blood offerings and Overtime spend survival margin", mapMarkerId: "shell-smert", faqQuestion: "What confirms the Smert ritual is ready?", faqAnswer: "The altar and screen turn red after all three pools activate; you must still inhabit the corpse and win The Convert memory." },
  ps5: { start: "Native PS5 application", goal: "Choose performance or quality mode", result: "Stable platform setup", risk: "Slayer Seal locks trophies on the save", faqQuestion: "Is Mortal Shell 2 PS5 Pro Enhanced?", faqAnswer: "Yes, the PlayStation Store labels it PS5 Pro Enhanced, although exact resolution and performance behavior remain patch-sensitive." },
  sidearms: { start: "Eight Resolve-powered offhands", goal: "Cover a weakness in the primary weapon", result: "Balance Patch 1-aware ranged, burst, or control option", risk: "Lute, Hystrix, and Repeater behavior changed in the first balance patch", mapMarkerId: "sidearm-naylshotte", faqQuestion: "Which Sidearm is the safest early upgrade?", faqAnswer: "Forgotten Crossbow remains the safest precision and pulling tool. Balance Patch 1 also doubled Troubadour's Lute damage and removed minimum Resolve requirements from Caged Hystrix and Triarch Repeater." },
  "hall-of-murmurs": { start: "Castigator's Keep Beacon", goal: "Clear Hall rewards and finish Egon separately", result: "750 Coins, Laterite, and Feed Me route", risk: "The dungeon uses Coins; Egon asks for Gloom", mapMarkerId: "dungeon-hall-of-murmurs", faqQuestion: "Is Egon inside Hall of Murmurs?", faqAnswer: "No. Hall of Murmurs is a short optional dungeon, while Egon is a separate NPC in Castigator's Keep central tower." },
  "npc-questlines": { start: "First NPC dialogue", goal: "Track requests, rests, movement, and rewards", result: "Resolved quest states and trophies", risk: "First-game routes for returning NPCs are not sequel evidence", mapMarkerId: "npc-egon", faqQuestion: "Why does an NPC quest appear stuck?", faqAnswer: "Exhaust dialogue, rest once at a Beacon, return, and verify the requested item name. Several retail quests change state only after that reset." },
  "night-mode": { start: "Gloombound Flame near Widow's Overlook", goal: "Summon Thestus and call the night", result: "Harder world, greater rewards, exclusive secrets", risk: "Night Mode and Slayer Seal are separate systems", mapMarkerId: "night-abandoned-outpost", faqQuestion: "Can Night Mode be turned off?", faqAnswer: "Yes. Return to Thestus at the top of Marrow Keep and choose Seek Daylight." },
  tarforge: { start: "Franz at Marrow Keep", goal: "Install four function parts and Endless Core", result: "Complete weapon, Sidearm, Tarstone, and refund services", risk: "Balance Patch 1 reduced smelting Gloom cost by 75%", mapMarkerId: "tarforge", faqQuestion: "Which part should be collected first?", faqAnswer: "Muradean Actuator is the first priority because it unlocks primary weapon enhancement and appears during the prologue." },
  trophies: { start: "Clean retail save without Slayer Seal", goal: "Complete platform list and hidden objectives", result: "PS5 Platinum or 52 platform achievements", risk: "Send Ova resets unfinished world and NPC states", faqQuestion: "Why does PS5 show one more trophy than Steam or Xbox?", faqAnswer: "PS5 adds the Platinum trophy, giving 53 total entries versus 52 achievements on Steam and Xbox in current lists." },
  "new-game-plus": { start: "Post-Zmey Gloom Siphon", goal: "Select Send Ova after cleanup", result: "New Purpose with carried build progress", risk: "Quests, Beacons, dungeons, bosses, chests, and Ovum reset", mapMarkerId: "marrow-keep", faqQuestion: "What is the most important pre-NG+ action?", faqAnswer: "Finish current-world NPC, trophy, key, chest, Beacon, and dungeon cleanup before selecting Send Ova." },
  tiel: { start: "Widow's Overlook / Martyr's Tomb route", goal: "Finish Rash Memory and collect the flask", result: "Tiel, the Acolyte", risk: "Low durability punishes forced late-dodge attempts", mapMarkerId: "shell-tiel", faqQuestion: "Must Great Arbiter be defeated before Tiel?", faqAnswer: "No. The arena is a route landmark, and Tiel's grave can be reached without making that optional fight a prerequisite." },
  proxima: { start: "Shattered Beacon north of Blackridge Pass", goal: "Finish Biosampler memory prompts", result: "Proxima, the Broodseeker", risk: "Hook direction changes against immovable targets", mapMarkerId: "shell-proxima", faqQuestion: "Must Shattered Beacon be fully cleansed?", faqAnswer: "No. Proxima is near the entrance and can be unlocked without completing the full Beacon interior." },
  lazlo: { start: "Royal Crypt / High Lord's Keep", goal: "Defeat Vellen and claim the post-arena body", result: "Lazlo, the Justiciar", risk: "Overheat opens a vulnerable armor-down window", mapMarkerId: "shell-lazlo", faqQuestion: "Is Lazlo awarded automatically after Vellen?", faqAnswer: "No. Continue into the chamber beyond the arena and interact with Lazlo's body." },
  sariel: { start: "Silent Steps", goal: "Trigger the ambush, break four revival tablets, finish the rematch", result: "Sariel, Clockwork Scythe, and Caged Hystrix route", risk: "The exit Sidearm is easy to leave behind", mapMarkerId: "shell-sariel", faqQuestion: "Why does Sariel keep reviving?", faqAnswer: "Four tablets or gravestones around the Chamber of Becoming arena enable the revivals; destroy all four before finishing the boss." },
  "chapel-key": { start: "Mushroom Village Beacon", goal: "Reveal Chapel Key and clear Shrine of Trials", result: "Axe and Dagger primary weapon", risk: "Chapel Key and Crypt Key open different dungeons", mapMarkerId: "chapel-key", faqQuestion: "Does Chapel Key require Night Mode?", faqAnswer: "No. Current retail walkthroughs place it behind the illusion arch near Mushroom Village in normal exploration; use it at the nearby locked chapel to enter Shrine of Trials." },
  "forgotten-crossbow": { start: "Blackridge Pass Beacon", goal: "Find Damp Key and open Flooded Village's central door", result: "Forgotten Crossbow Sidearm", risk: "The key and weapon are separate interactions", mapMarkerId: "sidearm-forgotten-crossbow", faqQuestion: "Is Forgotten Crossbow worth upgrading first?", faqAnswer: "Yes for patient players who use ranged pulls. Install Obsidian Lathe first, test the base firing rhythm, and keep the primary weapon strong enough to finish separated enemies." },
  "beginner-guide": { start: "Prologue / Marrow Keep", goal: "Build one repeatable Shell and weapon loop", result: "Safe first-playthrough foundation", risk: "Slayer Seal disables achievements on that save", mapMarkerId: "marrow-keep", faqQuestion: "Does Mortal Shell 2 have traditional character classes?", faqAnswer: "Shells function as the playable classes. Test Tiel and Proxima after the prologue, then develop one body's defining action before spreading currency across the roster." },
  monolith: { start: "Unfound Path / Obsidian Vault", goal: "Defeat the tendril-linked guardian", result: "Obsidian Vault branch cleared", risk: "Balance Patch 1 retimed selected attacks", mapMarkerId: "boss-monolith", faqQuestion: "Was Monolith nerfed?", faqAnswer: "Yes. Balance Patch 1 reduces its base damage by 19%, maximum health by 10%, and retimes several attacks, so older dodge videos may not match the current fight." },
};

export function getGuideEnhancement(article: GuideArticle) {
  const extra = guideExtras[article.slug];
  if (!extra) throw new Error(`Missing guide enhancement for ${article.slug}`);

  const faqs: GuideFaq[] = [
    { question: extra.faqQuestion, answer: extra.faqAnswer },
    { question: `What is the quick answer for ${article.keyword}?`, answer: article.quickAnswer },
    {
      question: "Is this guide verified for the current retail build?",
      answer: `Yes. This page is checked through Balance Patch 1 against ${article.sources.length} listed sources. Any route or effect that remains disputed is labeled instead of presented as confirmed.`,
    },
  ];

  return {
    ...extra,
    mapUrl: extra.mapMarkerId ? `/map?marker=${extra.mapMarkerId}` : "/map",
    faqs,
  };
}
